const Company = [
    { name: "Tesla", no: 146 },
    { name: "Apple", no: 50 },
    { name: "Microsoft", no: 75 },
    { name: "Google", no: 100 },
    { name: "Amazon", no: 200 },
    { name: "Facebook", no: 150 },
    { name: "Netflix", no: 80 },
    { name: "IBM", no: 120 },
    { name: "Intel", no: 90 },
    { name: "Oracle", no: 110 },
    { name: "Samsung", no: 95 },
    { name: "Twitter", no: 70 },
    { name: "Uber", no: 85 },
    { name: "Adobe", no: 60 },
    { name: "HP", no: 130 },
    { name: "Sony", no: 105 },
    { name: "Cisco", no: 115 },
    { name: "Nvidia", no: 75 },
    { name: "Snapchat", no: 65 },
    { name: "Salesforce", no: 55 },
    { name: "Spotify", no: 45 },
    { name: "Airbnb", no: 40 },
    { name: "Pinterest", no: 35 },
    { name: "LinkedIn", no: 30 },
    { name: "Walmart", no: 250 },
    { name: "Toyota", no: 300 },
    { name: "Coca-Cola", no: 150 },
    { name: "Nike", no: 75 },
    { name: "McDonald's", no: 200 },
    { name: "Starbucks", no: 250 },
    { name: "Disney", no: 150 },
    { name: "PepsiCo", no: 100 },
    { name: "Visa", no: 120 },
    { name: "Mastercard", no: 110 },
    { name: "Burger King", no: 90 }
];
export default Company;