const Problems = [
  { id: 1, status: 'ongoing', title: '1. Two Sum', solution: 'https://leetcode.com/problems/two-sum/solution', acceptance: '53.2%', difficulty: 'Easy', frequency: "23" },
  { id: 2, status: 'completed', title: '2. Add Two Numbers', solution: 'https://leetcode.com/problems/add-two-numbers/solution', acceptance: '39.8%', difficulty: 'Medium', frequency: "17" },
  { id: 3, status: 'null', title: '3. Longest Substring Without Repeating Characters', solution: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/solution', acceptance: '29.5%', difficulty: 'Medium', frequency: "12" },
  { id: 4, status: 'ongoing', title: '4. Median of Two Sorted Arrays', solution: 'https://leetcode.com/problems/median-of-two-sorted-arrays/solution', acceptance: '30.1%', difficulty: 'Hard', frequency: "9" },
  { id: 5, status: 'completed', title: '5. Longest Palindromic Substring', solution: 'https://leetcode.com/problems/longest-palindromic-substring/solution', acceptance: '25.6%', difficulty: 'Medium', frequency: "8" },
  { id: 6, status: 'ongoing', title: '6. ZigZag Conversion', solution: 'https://leetcode.com/problems/zigzag-conversion/solution', acceptance: '30.9%', difficulty: 'Medium', frequency: "7" },
  { id: 7, status: 'completed', title: '7. Reverse Integer', solution: 'https://leetcode.com/problems/reverse-integer/solution', acceptance: '25.3%', difficulty: 'Easy', frequency: "15" },
  { id: 8, status: 'null', title: '8. String to Integer (atoi)', solution: 'https://leetcode.com/problems/string-to-integer-atoi/solution', acceptance: '15.9%', difficulty: 'Medium', frequency: "6" },
  { id: 9, status: 'ongoing', title: '9. Palindrome Number', solution: 'https://leetcode.com/problems/palindrome-number/solution', acceptance: '47.2%', difficulty: 'Easy', frequency: "21" },
  { id: 10, status: 'completed', title: '10. Regular Expression Matching', solution: 'https://leetcode.com/problems/regular-expression-matching/solution', acceptance: '26.4%', difficulty: 'Hard', frequency: "4" },
  { id: 11, status: 'ongoing', title: '11. Container With Most Water', solution: 'https://leetcode.com/problems/container-with-most-water/solution', acceptance: '42.7%', difficulty: 'Medium', frequency: "11" },
  { id: 12, status: 'completed', title: '12. Integer to Roman', solution: 'https://leetcode.com/problems/integer-to-roman/solution', acceptance: '39.2%', difficulty: 'Medium', frequency: "9" },
  { id: 13, status: 'null', title: '13. Roman to Integer', solution: 'https://leetcode.com/problems/roman-to-integer/solution', acceptance: '53.8%', difficulty: 'Easy', frequency: "18" },
  { id: 14, status: 'ongoing', title: '14. Longest Common Prefix', solution: 'https://leetcode.com/problems/longest-common-prefix/solution', acceptance: '35.6%', difficulty: 'Easy', frequency: "14" },
  { id: 15, status: 'completed', title: '15. 3Sum', solution: 'https://leetcode.com/problems/3sum/solution', acceptance: '28.9%', difficulty: 'Medium', frequency: "7" },
  { id: 16, status: 'ongoing', title: '16. 3Sum Closest', solution: 'https://leetcode.com/problems/3sum-closest/solution', acceptance: '45.3%', difficulty: 'Medium', frequency: "10" },
  { id: 17, status: 'completed', title: '17. Letter Combinations of a Phone Number', solution: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/solution', acceptance: '47.1%', difficulty: 'Medium', frequency: "13" },
  { id: 18, status: 'null', title: '18. 4Sum', solution: 'https://leetcode.com/problems/4sum/solution', acceptance: '32.5%', difficulty: 'Medium', frequency: "6" },
  { id: 19, status: 'ongoing', title: '19. Remove Nth Node From End of List', solution: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/solution', acceptance: '36.2%', difficulty: 'Medium', frequency: "9" },
  { id: 20, status: 'completed', title: '20. Valid Parentheses', solution: 'https://leetcode.com/problems/valid-parentheses/solution', acceptance: '40.5%', difficulty: 'Easy', frequency: "16" },
  { id: 21, status: 'ongoing', title: '21. Merge Two Sorted Lists', solution: 'https://leetcode.com/problems/merge-two-sorted-lists/solution', acceptance: '52.1%', difficulty: 'Easy', frequency: "19" },
  { id: 22, status: 'completed', title: '22. Generate Parentheses', solution: 'https://leetcode.com/problems/generate-parentheses/solution', acceptance: '65.3%', difficulty: 'Medium', frequency: "11" },
  { id: 23, status: 'null', title: '23. Merge k Sorted Lists', solution: 'https://leetcode.com/problems/merge-k-sorted-lists/solution', acceptance: '43.8%', difficulty: 'Hard', frequency: "8" },
  { id: 24, status: 'ongoing', title: '24. Swap Nodes in Pairs', solution: 'https://leetcode.com/problems/swap-nodes-in-pairs/solution', acceptance: '47.9%', difficulty: 'Medium', frequency: "10" },
  { id: 25, status: 'completed', title: '25. Reverse Nodes in k-Group', solution: 'https://leetcode.com/problems/reverse-nodes-in-k-group/solution', acceptance: '44.2%', difficulty: 'Hard', frequency: "6" },
  { id: 26, status: 'ongoing', title: '26. Remove Duplicates from Sorted Array', solution: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/solution', acceptance: '46.8%', difficulty: 'Easy', frequency: "20" },
  { id: 27, status: 'completed', title: '27. Remove Element', solution: 'https://leetcode.com/problems/remove-element/solution', acceptance: '47.5%', difficulty: 'Easy', frequency: "14" },
  { id: 28, status: 'null', title: '28. Implement strStr()', solution: 'https://leetcode.com/problems/implement-strstr/solution', acceptance: '35.9%', difficulty: 'Easy', frequency: "11" },
  { id: 29, status: 'ongoing', title: '29. Divide Two Integers', solution: 'https://leetcode.com/problems/divide-two-integers/solution', acceptance: '16.8%', difficulty: 'Medium', frequency: "5" },
  { id: 30, status: 'completed', title: '30. Substring with Concatenation of All Words', solution: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/solution', acceptance: '26.1%', difficulty: 'Hard', frequency: "3" },
  // ... continue with more fake data
];

export default Problems;