const topics = {
    "Array": 1678,
    "String": 705,
    "Hash Table": 613,
    "Dynamic Programming": 510,
    "Math": 502,
    "Sorting": 406,
    "Greedy": 365,
    "Binary Search": 269,
    "Tree": 229,
    "Depth-First Search": 288,
    "Database": 272,
    "Breadth-First Search": 228,
    "Matrix": 225,
    "Bit Manipulation": 214,
    "Two Pointers": 203,
    "Binary Tree": 175,
    "Heap (Priority Queue)": 169,
    "Prefix Sum": 163,
    "Stack": 155,
    "Simulation": 153,
    "Graph": 142,
    "Counting": 133,
    "Design": 123,
    "Sliding Window": 119,
    "Backtracking": 102,
    "Enumeration": 86,
    "Union Find": 82,
    "Linked List": 75,
    "Ordered Set": 61,
    "Monotonic Stack": 58,
    "Number Theory": 55,
    "Trie": 53,
    "Divide and Conquer": 47,
    "Segment Tree": 46,
    "Bitmask": 45,
    "Queue": 45,
    "Recursion": 45,
    "Binary Search Tree": 40,
    "Memoization": 38,
    "Binary Indexed Tree": 38,
    "Geometry": 37,
    "Hash Function": 36,
    "Combinatorics": 33,
    "Topological Sort": 32,
    "String Matching": 30,
    "Shortest Path": 28,
    "Rolling Hash": 28,
    "Game Theory": 25,
    "Interactive": 23,
    "Data Stream": 20,
    "Brainteaser": 16,
    "Monotonic Queue": 15,
    "Randomized": 12,
    "Merge Sort": 12,
    "Iterator": 9,
    "Concurrency": 9,
    "Doubly-Linked List": 8,
    "Probability and Statistics": 7,
    "Quickselect": 7,
    "Counting Sort": 6,
    "Bucket Sort": 6,
    "Suffix Array": 6,
    "Minimum Spanning Tree": 5,
    "Shell": 4,
    "Line Sweep": 4,
    "Reservoir Sampling": 4,
    "Strongly Connected Component": 3,
    "Eulerian Circuit": 3,
    "Radix Sort": 3,
    "Rejection Sampling": 2,
    "Biconnected Component": 1
};
 export default topics;